baseURL       : "https://adityam.github.io/aruna-poems/"

languageCode  : "en-us"
title         : "Aruna Mahajan's Poems"
theme         : coursepage

pluralizelisttitles: fasle
preserveTaxonomyNames: true

enableGitInfo: true

markup:
  defaultMarkdownHandler: "blackfriday"

metaDataFormat: yaml
publishDir    : docs

